config/routes.rb
Rails.application.routes.draw do
  resources :specials, only: [:show, :index, :create, :new, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/special.rb
class Special < ApplicationRecord
	validates :day, presence: true, length: { minimum: 5, maximum: 10}
	validates :title, presence: true, length: { minimum: 3, maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController

def show
	@special = Special.find(params[:id])
end

def index
	@specials = Special.all
end

def new
	@special = Special.new
end

def edit
	@special = Special.find(params[:id])
end

def create
	@special = Special.new(params.require(:special).permit(:day, :title, :description))
	if @special.save
		flash[:notice] = "Special was created successfully"
 		redirect_to (@special)
	else render 'new'

	end
end

def update
	@special = Special.find(params[:id])
	if @special.update(params.require(:special).permit(:day, :title, :description))
		flash[:notice] = "Special was updated successfully"
		redirect_to @special
	else
		render 'edit'
	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Localdeals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%=msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/specials/edit.html.erb
<h1>Edit Special</h1>

<% if @special.errors.any? %>
<h2>The Following errors prevented the special from being saved:</h2>
	<ul>
		<% @special.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_with(model: @special, local: true)  do |f| %>

<p>
	<%= f.label :day %><br/>
	<%= f.text_field :day %>
</p>

<p>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :description %><br/>
	<%= f.text_area :description %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/specials/index.html.erb
<h1>Specials for the Day</h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @specials.each do |special| %>
			<tr>
				<td><%= special.title %></td>
				<td><%= special.description %></td>
				<td>Placeholder</td>
			</tr>
		<% end %>
	</tbody>

</table>

app/views/specials/new.html.erb
<h1>Create New Special</h1>

<% if @special.errors.any? %>
<h2>The Following errors prevented the special from being saved:</h2>
	<ul>
		<% @special.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_with scope: :special, url: specials_path, local: true do |f| %>

<p>
	<%= f.label :day %><br/>
	<%= f.text_field :day %>
</p>

<p>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :description %><br/>
	<%= f.text_area :description %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/specials/show.html.erb
<h1>Showing Special details</h1>

<p><strong>Title:</strong><%=@special.title %></p>
<p><strong>Description:</strong><%=@special.description %></p>